// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: fRff5NdcfsSzGJTDR4rK8j
// Component: 36BHbTduQm
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import LinkButton from "../../LinkButton"; // plasmic-import: kCnM-velVmy/component

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_signup_modal.module.css"; // plasmic-import: fRff5NdcfsSzGJTDR4rK8j/projectcss
import * as sty from "./PlasmicSignupButton.module.css"; // plasmic-import: 36BHbTduQm/css

export type PlasmicSignupButton__VariantMembers = {};

export type PlasmicSignupButton__VariantsArgs = {};
type VariantPropType = keyof PlasmicSignupButton__VariantsArgs;
export const PlasmicSignupButton__VariantProps = new Array<VariantPropType>();

export type PlasmicSignupButton__ArgsType = {};
type ArgPropType = keyof PlasmicSignupButton__ArgsType;
export const PlasmicSignupButton__ArgProps = new Array<ArgPropType>();

export type PlasmicSignupButton__OverridesType = {
  root?: p.Flex<typeof LinkButton>;
};

export interface DefaultSignupButtonProps {
  className?: string;
}

function PlasmicSignupButton__RenderFunc(props: {
  variants: PlasmicSignupButton__VariantsArgs;
  args: PlasmicSignupButton__ArgsType;
  overrides: PlasmicSignupButton__OverridesType;
  dataFetches?: PlasmicSignupButton__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <LinkButton
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames("__wab_instance", sty.root)}
      href={"#" as const}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: typeof LinkButton;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSignupButton__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSignupButton__VariantsArgs;
    args?: PlasmicSignupButton__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicSignupButton__Fetches;
  } & Omit<PlasmicSignupButton__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicSignupButton__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicSignupButton__ArgProps,
      internalVariantPropNames: PlasmicSignupButton__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicSignupButton__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSignupButton";
  } else {
    func.displayName = `PlasmicSignupButton.${nodeName}`;
  }
  return func;
}

export const PlasmicSignupButton = Object.assign(
  // Top-level PlasmicSignupButton renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicSignupButton
    internalVariantProps: PlasmicSignupButton__VariantProps,
    internalArgProps: PlasmicSignupButton__ArgProps
  }
);

export default PlasmicSignupButton;
/* prettier-ignore-end */
